### ISSUE TITLE
Slack link no longer active

### ISSUE THREAD

**Issue by igoldsteinh** [slequime/nosoi#11]
I tried to join the nosoi slack but the link on the github says "This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link." Can I get a new link? Thanks!

**Comment by slequime** [comment]
Hi! So sorry, the Slack invite does have an expiration date... I've updated the link in the description. Or you can use [this link](https://join.slack.com/t/nosoi/shared_invite/zt-kk3mfk7m-d9vbb5Ze7amnR54eSvdoCw), which should work too. Let me know if you have any troubles!
