### ISSUE TITLE
getTransmissionTree() failing with unstructured simulation

### ISSUE THREAD

**Issue by igoldsteinh** [slequime/nosoi#12]
Hi there, I'm using R 4.0.2 and nosoi 1.0.3. I tried to use getTransmissionTree() on the example simulation provided in https://slequime.github.io/nosoi/articles/none.html#core-functions with no dual infections. When I did this I got the following error:

Error: Assigned data `c(...)` must be compatible with row subscript `counter`. x 1 row must be assigned. x Assigned data has 10 rows. i Row updates require a list value. Do you need `list()` or `as.list()`?

I have found that getTransmissionTree() seems to work find for simulations with discrete spatial structure (as is used in the example for getTransmissionTree()).  Any insights into what is going on? Thanks for your help!

**Comment by pbastide** [comment]
Indeed, it seems that the case with no structure makes function `getTransmissionTree` crash...
I'll try to fix this as soon as possible.
Thank you for pointing this bug out !

**Comment by slequime** [comment]
Thanks @pbastide, I've merged. Should work! Thanks @igoldsteinh for pointing this out!
