### ISSUE TITLE
Discrepancy in getR0 counts

### ISSUE THREAD

**Issue by igoldsteinh** [slequime/nosoi#14]
Hi there. I noticed there seems to be a discrepancy between the reported number of inactive hosts used in the calculation of R0, and the actual number of recorded values in the R0 distribution (N.inactive vs  length(R0.dist)). For instance in https://slequime.github.io/nosoi/articles/output.html#r_0, there are apparently 117 inactive hosts, but there are 120 values in the R0 distribution. Based on getTableHosts, it looks like 117 is the correct number. Any insights as to the extra values appreciated. Thanks!

**Comment by slequime** [comment]
Hi @igoldsteinh ,
@pbastide was again much more reactive than I was. The initial problem was a badly coded function that retained some hosts that did transmit but were not out of the simulation yet. The new version of getR0 corrects that problem (and is much more efficient too).

**Comment by igoldsteinh** [comment]
Sorry for the late reply, thanks for the response and the fix!
