### ISSUE TITLE
where to find this, ~/Dropbox/C-Leuven Projects/Nosoi/Nosoi-Rpackage/Dengue Data/routes.dat

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [slequime/nosoi#16]

**Comment by slequime** [comment]
Dear @LiXingguangBrandonStark ,
As written in the associated tutorial (see Air Transporation section on [this page](https://slequime.github.io/nosoi/articles/examples/dengue.html), the files can be downloaded at [OpenFlights.org](https://openflights.org/data.html).
Hope that helps!

**Comment by LiXingguangBrandonStark** [comment]
thanks, I find that file.
