### ISSUE TITLE
is this error in your example file?

### ISSUE THREAD

**Issue by liamxg** [slequime/nosoi#17]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/46078579/156880339-a70ab89c-c9cb-45ec-8800-7d82478bafd0.png">

**Comment by slequime** [comment]
I am not sure where this is supposed to be? Can you provide more details please?

**Comment by LiXingguangBrandonStark** [comment]
country_code.csv this file.

**Comment by LiXingguangBrandonStark** [comment]
can you find this file?

**Comment by LiXingguangBrandonStark** [comment]
GADM.admin0 <- readOGR(dsn = "/path/to/your/shapefiles/.", layer = "gadm36_0") where to find this file, thanks.

**Comment by slequime** [comment]
> country_code.csv this file.

It was indeed a typo. This has been corrected in the current repository.

> GADM.admin0 <- readOGR(dsn = "/path/to/your/shapefiles/.", layer = "gadm36_0") where to find this file, thanks.

Country spatial polygons come from [GADM](https://gadm.org/data.html), as written in the tutorial.

Hope that helps!

**Comment by LiXingguangBrandonStark** [comment]
in GADM, we can download them separately, how to integrate the five countries together, thanks.
