### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [slequime/nosoi#18]
@GuyBaele @pbastide @sdellicour @slequime: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/igraph-0.10/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

It's likely that the problems are related to https://github.com/briatte/ggnetwork/issues/74, which has been fixed on GitHub but hasn't found its way to CRAN yet.

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph@igraph-0.10")` .

We're planning to release igraph 2.0.0 just before CRAN's closing on Christmas. This should give us at least until mid-January to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
New anticipated release date: January 12.

**Comment by krlmlr** [comment]
We're planning to send igraph to CRAN on January 23, we're still seeing failures with this package: https://github.com/igraph/rigraph/blob/main/revdep/problems.md .

**Comment by slequime** [comment]
This issue should be fixed with commit #21 #
