### ISSUE TITLE
Error when run `nosoiSim()` in `ebola.Rmd` file

### ISSUE THREAD

**Issue by liamxg** [slequime/nosoi#22]
Dear @slequime,

Please see below:

Starting the simulation
Initializing ...Error in stopifnot(isTRUEorFALSE(verbose)) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/data.table/R/data.table.rdb' is corrupt
In addition: Warning messages:
1: In stopifnot(isTRUEorFALSE(verbose)) :
  restarting interrupted promise evaluation
2: In stopifnot(isTRUEorFALSE(verbose)) :
  internal error -3 in R_decompress1

**Comment by slequime** [comment]
Hello @liamxg ,
It seems this is a problem with your installation of the data table package. I cannot replicate the issue. Reinstalling the data.table (maybe nosoi too, just in case) package might solve the problem.
