### ISSUE TITLE
_R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check errors

### ISSUE THREAD

**Issue by rsbivand** [slequime/nosoi#5]
Many of the suggested packages are not protected by warnings or messages if not installed, and R CMD check is run without requiring the presence of these packages. I run regular reverse dependency checks for spatial packages, here **raster**, and your omission causes many unnecessary installs. Tidyness in not throwing errors when checking without suggested packages being available is very good practice.

**Comment by slequime** [comment]
Hi,
Thanks for letting us know. We are currently working on correcting that!

**Comment by slequime** [comment]
Hi,
This issue should have been corrected (by @pbastide ). Let us know if there are any remaining issues. Thanks!
